name: Update PIF

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-pif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update PIF
        run: |
          chmod +x Toolbox-patcher/scripts/update_pif.sh
          ./Toolbox-patcher/scripts/update_pif.sh

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Toolbox-data/Pif-props.json
          # Check if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update PIF props [skip ci]"
            git push
          fi
